sudo: false
language: node_js
node_js:
  - 9.11.1 # use nodejs v10 LTS

branches:
  only:
    - master # build master branch only
cache:
  directories:
    - node_modules
    #- themes 主题没有更改时可以缓存

before_install:
  - npm install -g hexo-cli # 安装 hexo
  - npm install -unsafe-perm -verbose -g hexo

install:
  - npm install # 安装 package.json 中的插件

script:
  - hexo generate # generate static files
  

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public