name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: 1. git checkout...
      uses: actions/checkout@v2

    - name: 2. setup nodejs...
      uses: actions/setup-node@v2
      with:
          node-version: '14.18.1'

    - name: 3. install hexo...
      run: |
        npm install hexo-cli -g 
        npm install hexo-deployer-git –save
        npm install

    - name: 4. hexo generate public files...
      run: |
        hexo clean
        hexo g
    
    # 提交到我们的存放静态资源的仓库
    - name: 5. Config Private Key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }} #此处的PRIVATE_KEY 是配置私有库时settings-》secrets的名称
      run: |
         mkdir -p ~/.ssh/
         echo "$PRIVATE_KEY" > ~/.ssh/github_rsa
         chmod 600 ~/.ssh/github_rsa
         ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: 6. Config Git
      run: |
         git config --global user.name 'onelee85'
         git config --global user.email 'onelee85@gmail.com'
    - name: 7. Deploy
      run: |
        rm -rf .deploy_git
        hexo d

